version: '3.0' 
services:        
        role-service:
                container_name: role-service
                image: role-service
                build: ./role-service
                ports: 
                        - "8082:80"
        department-service:
                container_name: department-service
                image: department-service
                build: ./department-service
                ports: 
                        - "8083:80"
        office-service:
                container_name: office-service
                image: office-service
                build: ./office-service
                ports:
                        - "8084:80"
        person-service:
                container_name: person-service
                image: person-service
                build: ./person-service
                ports:
                        - "8081:80"
