apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-deployment
  labels:
    app: office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: office
  template:
    metadata:
      labels:
        app: office
    spec:
      containers:
      - name: office-service
        image: lordblackfish/office-service:1
        ports:
        - containerPort: 80 
      imagePullSecrets:
        - name: regcred
